version: '3.8'
services:
  cass1:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cass1,cass2,cass3 
      - CASSANDRA_SEEDS=cass1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=pass123
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - ./cass1:/docker-entrypoint-initdb.d
  cass2:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cass1,cass2,cass3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=pass123
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
  cass3:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cass1,cass2,cass3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=pass123
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    depends_on:
      - cass1
      - cass2
      - cass3
    ports:
      - '3000:3000'